---
output: pdf_document
---

How can we ensure that patients receive the right medical interventions at the right time? And beyond the individual, how can we determine where to intervene to promote public health? These questions cut to the core of medical and public health aspirations, but it is only in the past few decades that methodological and technological advances have progressed to the point where these questions can be investigated in a data-driven, empirical way. These questions have been considered by both fields since their inception, but this kind of tailoring has historically only been possible in non-systematic and qualitative ways. While clinicians make treatment decisions after eliciting details of a patient's disease history and considering their characteristics and comorbidities, the vast majority of evidence from randomized clinical trials (RCTs) are very stylized circumstances where efficacy for an intervention was compared to a placebo and extensive inclusion/exclusion criteria are used to reduce heterogeneity as much as possible. New trial designs are needed to bridge this gap.

Precision medicine, and precision health more broadly, endeavors to use statistical methods to match "the right patient to the right treatment at the right time" in an evidence-based way \citep{kosorok2015adaptive, kosorok2019precision}. The majority of this literature has focused on how to estimate optimal dynamic treatment regimes including Q-learning, A-learning, Outcome Weighted Learning, and Residual Weighted Learning and many others including extensions of these methods. The major design innovation from this movement is the  Sequential multiple-assignment randomized trial (SMART), which was developed to provide information that could be used for sequencing treatments \citep{lei2012smart}. The randomization probabilities in a SMART are typically static throughout the course of the trial, but the randomization probabilities for later stages can depend on the assignment and observed response from earlier stages. Trial designs for the single-stage decision problem where the expected treatment response is a function of patient covariates is relatively underexplored. Interaction effects are necessarily more difficult to estimate than main effects, and more efficient trial designs are needed to answer questions about tailoring treatments to patients. 

This dissertation proposes multiple randomization methods that can be used to improve the estimation of dynamic treatment regimes (DTRs) and evaluate multilevel interventions that would improve the efficiency of trying to answer scientific questions about where and when to intervene to maximally improve the health of individuals and consequently the population. The next section reviews the existing literature on and history of precision medicine, response-adaptive randomization methods that change allocation probabilities based on accumulating evidence, and the parallel literature on "bandit" problems that has evolved primarily in the computer science and operations research literatures. 

   Chapter one extends the "drop the loser" rule to the general case where the treatment effect can be a function of patient covariates \citep{ivanova2000drop, ivanova2003play}; it can also be viewed as extending the work on "best arm identification" for the multi-armed bandit (MAB) problem to the contextual multi-armed bandit problem (CMAB). 
   
   In chapter two, we extend this approach to the case where there is structure between interventions and information from one treatment assignment could provide information about the expected response on a different treatment. This setting naturally arises in dose finding studies where the response at one dosage can provide information about the expected response at a different dosage. We consider two cases: one where there is a safety constraint and one without a safety constraint. In the case where there is no safety constraint, treatments that are known to be suboptimal can still be assigned if they are more informative about the optimal dose than other treatments. The structure of the dose-response relationship determines whether this is the case; in the simple case where there is a linear relationship between dose and response the optimal design would only allocate patients to the highest or lowest dose for example.
   
   We investigate a trial design for multilevel interventions when the individual component can be completely randomized but all participants at the group level must receive the intervention. With these constraints at the group level we propose a Stepped Wedge design where the time at which a group receives the intervention is randomized \citep{gambia1987gambia, hussey2007design}. We show the efficacy of this method through simulation studies and provide a formula for sample size calculation. 