---
output: pdf_document
---

I will now outline the planned work to bring this project to completion. I will complete the proofs for the PDC minimax theorem (if you are reading this, hopefully they will be available during the presentation). For the simulation, an additional scenario using a different function class $\mcF$, potentially decision trees of a fixed depth, will be added. In addition I will add two additional methods for comparison: 1) \cite{foster2018practical} SquareCB. While this is a method for reducing the
in-sample regret, it will provide insight into the tradeoff between in-sample 
and out-of-sample performance DTR estimation for the CMAB problem, and 2)
SCUBA \cite{guo2017subgroup}. 
 
Finally a "null" scenario will be defined to probe the method. "Null" scenarios do not map neatly when the goal is function estimation rather than hypothesis testing. When no treatment is more effective than any other treatment the value of all DTRs are the same. Minimizing the population expected regret in this scenario is trivial because it is impossible to fail (everything is equally ineffective). An alternative performance metric we can investigate are the probability than an arm that is not suboptimal is removed prematurely. 