---
output: pdf_document
---

The socio-ecological model of health posits that health is not simply a function of an individual's
biology and choices, but the interaction of factors at the individual, interpersonal, community, and societal levels \citep{bronfenbrenner1992ecological}. This model has been adopted by the National Institute of Minority Health and Health Disparities (NIMHD) Research Framework which posits that these myriad factors form and perpetuate health inequities. Social determinants of health (SDOH) comprise the conditions in which individuals grow, live, work, and play, as well as the economic, political, and societal forces that shape these conditions. Decades of observational studies have consistently documented that the interaction between factors across multiple levels impact health, which suggests that multilevel interventions could substantially improve health equity-oriented outcomes compared to interventions that focus on a single level. Despite this, moving from single- to multi-level interventions that include one or more SDOH as an intervention target has lagged – in no small part due to methodological challenges \citep{agurs2019designing}. Analytic methods and trial designs are needed that address the complexity of multilevel interventions: there are structured relationships between different levels such as individuals living in a neighborhood or the employees hired by a firm, and there are often different constraints on randomization at different levels of SDOH. 

# Motivating Trial

Employment is a key SDOH with both economic and social benefits. Unemployment precipitates a cascade of psychological, emotional, coping, and behavioral changes at the individual and interpersonal levels in response to the stresses that job loss brings \citep{mantler2005coping}. These risks disproportionately impact socioeconomically disadvantaged (SED) populations and increase the odds of poor chronic disease outcomes \citep{roelfs2011losing}.  Workplace environment is also a significant predictor of a wide range of health outcomes. For example, new hires from SED groups after an unemployment episode may face negative employer bias towards them and a low expectation of performance that can exacerbate the stresses already faced from unemployment. These negative expectations can become a self-fulfilling prophecy by making it difficult to succeed at work and perpetuating unemployment recurrence.  

The NC Works4Health: Reducing Chronic Disease Risks in Socioeconomically Disadvantaged, Unemployed Populations (NCW4H) study includes an ongoing clinical trial (NCT04815278) to evaluate the effectiveness of a multilevel intervention to reduce chronic disease risks in SED, unemployed populations. The intervention is designed to target both individual- and group-level components by (a) embedding prevention efforts through healthy lifestyle supports among unemployed adults receiving publicly-funded job search services at the individual level, and (b) enhancing supervisor support for SED hires at the employer level. Initially, both individuals and employers were to be randomized, with individuals randomized using a permuted block approach and employers randomized using a biased coin approach, but changes in the post-COVID labor market necessitated a change to the employer enrollment and randomization strategy. 

The vast majority of studies testing employment interventions have offered health promotion programs in the workplace; far fewer have tested supervisor support \citep{hammer2016intervention} or multilevel interventions \citep{neshteruk2021implementation}. Among these, randomization is often feasible at, and has been conducted at the organizational level. Testing multilevel interventions across individual and employer levels that reflect the real-world trajectory of unemployed study participants moving into new work settings, however, required a novel randomization approach at the employer level.  

# Proposed Design

Our design combines complete randomization at the individual level with a stepped wedge design at the group level. The randomization at the individual level can be conducted using existing methods such as permuted block randomization. We propose a stepped wedge design at the group level: as groups enroll they begin in the control group, and the period that they switch from the control group to the intervention will be randomized. We consider the case where there is an open cohort of both individuals and groups – new groups may enroll throughout the course of the study, and an individual’s membership in a group can change. For example, an employer may hire or fire employees throughout the duration of their participation in the study. 

We consider a cohort stepped wedge design with open cohorts of individuals and groups. Participants enroll in the trial and are individually randomized, and participants are part of (or join, in the case of a motivating trial) a group that is randomized using a stepped wedge design.  The primary outcome is measured at the individual level and is a function of individual and group characteristics and individual and group level intervention effects. The expected response for individual $i = 1, \ldots, n$ in cluster $j = 1, \ldots, J$, at time $t = 1, \ldots, T$ is given by

$$\E[Y_{ijt}] = X_{ijt}^T\beta_{\rm ind} + W_{jt}^T \beta_{\rm grp} + A_{i}\tau_{\rm ind} + A_{ijt} \tau_{\rm grp} + A_i A_{ijt} \gamma$$
Where $A_i$ is an indicator of whether individual $i$ was in the intervention condition, and $A_{ijt}$ indicates whether cluster $j$, the cluster individual $i$ belongs to, was treated by time $t$. The individual-level treatment effect is denoted by $\tau_{\rm ind}$, the group-level treatment effect by $\tau_{\rm grp}$, and the interaction between both interventions by $\gamma$. The expected response is also a function of their individual characteristics $X_{ijt}$ and the organization’s characteristics $W_{jt}$. 

I propose to study two potential study objectives:

1) to test the intervention main effects: $H_0: \tau_{\rm ind} = 0$ vs. $H_1: \tau_{\rm ind} \neq 0$ and $H_0: \tau_{\rm grp} = 0$ vs. $H_1: \tau_{\rm grp} \neq 0$ , and 

2) to test the combined effect of both interventions: $H_0: (\tau_{\rm ind} + \tau_{\rm grp} + \gamma) = 0$ vs. $H_1: (\tau_{\rm ind} + \tau_{\rm grp} + \gamma) \neq 0$. 

I will derive closed-form sample size formulas for these objectives based on analyzing the data using Generalized Estimating Equations (GEE). Sample size calculators do not currently exist for this setting outside of bespoke simulation studies \citep{ouyang2022sample}. While some calculators allow for nested clusters, for example randomizing wards within a hospital to an intervention at different times, this is distinct from having interventions at both the group and group-member level. 

I propose to evaluate the relative efficiency of this design with two natural competitors: 1) the completely randomized design where both individuals and groups are randomized to either the intervention or control, and 2) the group-only design where both individuals and groups are randomized using a stepped wedge design. We will derive the asymptotic relative efficiency of the treatment effect estimators from these designs and conduct a simulation study to evaluate their finite sample relative performance. We anticipate that the completely randomized design will be the most efficient design, though it is often not possible to implement in this research area, while our design will provide meaningful improvement over the group-only design. 
